export const ImageAssets = {
    LoginImage: require('./login_image.jpg'),
    RightArrow: require('./right_arrow.png'),
    UserImage: require('./userimage.jpg'),
    MyMeetupImage:require('./MyMeetupImage.png'),
    backbutton:require('./backbutton.png'),
    SubwayLoge:require('./subwayLoga.png'),
    Subway1:require('./subway1.png'),
    Subway2:require('./subway2.png'),
    Subway3:require('./subway3.png'),
    Subway4:require('./subway4.png'),
    Subway5:require('./subway5.png'),
    HaldiramLogo:require('./HaldiramLogo.png'),
    Dosa1:require('./dosa1.png'),
    Dosa2:require('./dosa2.png'),
    KFCLogo:require('./KFCLogo.png'),
    KFC1:require('./kfc1.png'),
    KFC2:require('./kfc2.png'),
    MacDLogo:require('./macdLogo.png'),
    MacD:require('./macd.png'),
    BikanerwalaLogo:require('./bikanerwalaLogo.png'),
    AddButton:require('./add.png'),
    Firebutton:require('./fire.png'),
    Minus:require('./minus.png'),
    Add:require('./addcart.png'),
    Thali:require('./Thali.png'),
    User:require('./user.png'),
    UserProfile:require('./userprofile.png'),
    cross:require('./cross.png'),
    userProfile:require('./userLogo.png'),
    accessCard:require('./accessCard.png'),
    pendingVisit:require('./visitors.png'),
    myRSVP:require('./myRSVP.png'),
    discount:require('./discountsAvailable.png'),
    helpSupport:require('./helpSupport.png'),
    settings:require('./settings.png'),
    feedback:require('./feedback.png'),
    services:require('./services.png'),
    logout:require('./logout.png')
}